### ISSUE TITLE
Open Discussions and Wikis?

### ISSUE THREAD

**Issue by rakino** [guixcn/guix-channel#2]
Wikis 可以用來放服務的文檔，然後 Discussions……不知道拿來幹嘛但看起來感覺有用的樣子（

**Comment by Z572** [comment]
wikis 确实有用，Discussions 感觉没啥用，在 https://github.com/guixcn/help 或者 tg/matrix/irc 问就行了吧

**Comment by rakino** [comment]
OK

**Comment by Z572** [comment]
wiki 应该开了，可以试下？

**Comment by rakino** [comment]
Wiki 好像也是一個 git 倉庫（<https://github.com/guixcn/guix-channel.wiki.git>），你能不能 push？

**Comment by Z572** [comment]
可以 push ，网页上你应该也能修改？

**Comment by rakino** [comment]
現在有修改的選項了
